services:
  youtube-streams:
    build:
      context: .
      args:
        BUILD_IMAGE: python:3.14-slim
        RUNTIME_IMAGE: python:3.14-slim
    volumes:
      - ./src:/app/src
    ports:
      - "23457:8000"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - EXCLUDED_CATEGORIES=${EXCLUDED_CATEGORIES:-Gaming,Sports,Film & Animation,Howto & Style}
      - SEARCH_QUERY=${SEARCH_QUERY:-cam live webcam beach wildlife aquarium space harbor park mountain coast -gameplay -playing -subscriber -donation -follower -facecam -reaction -chatting -gaming -fortnite -troll -asmr -twitch}
      - UPDATE_INTERVAL_HOURS=${UPDATE_INTERVAL_HOURS:-5}
      - MAX_VIDEOS_PER_CYCLE=${MAX_VIDEOS_PER_CYCLE:-1000}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    restart: unless-stopped
